#! /bin/bash

if ! pgrep "polybar" > /dev/null 2>&1 ; then
    polybar bsp &
    sleep 0.2
fi

# Only one monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc desktop 6 -l monocle
bspc desktop 2 -l monocle

bspc config border_width         2
bspc config window_gap          5
bspc config bottom_padding          -5
bspc config left_padding          -5
bspc config right_padding          -5
bspc config top_padding          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config honor_size_hints    true


bspc config external_rules_command "$HOME/.config/bspwm/bspwm-rules"

# for compatibility with java applications like intellij-idea
wmname LG3D
